global:
  scrape_interval: 5s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'api'
    static_configs:
      - targets: ['api0:8080', 'api1:8080','api2:8080']
  - job_name: 'services'
    static_configs:
      - targets: ['email:8081']
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
