global:
  scrape_interval: 5s
  evaluation_interval: 5s

alerting:

rule_files:

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["127.0.0.1:9090"]
  - job_name: "api"
    static_configs:
      - targets: ["api0:8080", "api1:8080", "api2:8080"]
  - job_name: "kafka"
    static_configs:
      - targets: ["kafexporter:9308"]
  - job_name: 'nginx'
    static_configs:
      - targets: ['proxexporter:9113']
