version: "3"
services:
  # Proxy
  proxy:
    build: ./games_proxy
    ports:
      - "80:80"
      - "8080"
    depends_on:
      - api0
      - api1
      - api2
    restart: on-failure
    networks:
      - exchange
  proxexporter:
    image: nginx/nginx-prometheus-exporter:latest
    depends_on:
        - proxy
    command: '--nginx.scrape-uri=http://proxy:8080/stub_status'
    ports:
      - '9113'
    restart: on-failure
    networks:
        - exchange

  # APIS
  api0:
    build: ./games_api
    ports:
      - "8080"
    depends_on:
      - database
      - kafka
    restart: on-failure
    networks:
      - exchange
  api1:
    build: ./games_api
    ports:
      - "8080"
    depends_on:
      - database
      - kafka
    restart: on-failure
    networks:
      - exchange
  api2:
    build: ./games_api
    ports:
      - "8080"
    depends_on:
      - database
      - kafka
    restart: on-failure
    networks:
      - exchange

  # DataBase
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    restart: on-failure
    networks:
      - exchange
  # MongoDB Exporter 
  # Still needs more work to fix not interacting with prometheus..
  dbexporter:
    image: bitnami/mongodb-exporter:latest
    environment:
        - MONGODB_URI=mongodb://monitor:reader@database:27017/?authSource=Games
    ports:
        - "9216"
    depends_on:
        - database
    restart: on-failure
    networks:
        - exchange
  # Email Service
  email:
    build: ./games_email
    ports:
      - "8081"
    depends_on:
      - kafka
    restart: on-failure
    networks:
      - exchange

  # Zoo Keeper: https://hub.docker.com/r/bitnami/zookeeper !!might not be needed!!
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zoo_data:/bitnami
    restart: on-failure
    networks:
      - exchange

  # Kafka: https://hub.docker.com/r/bitnami/kafka
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - kafka_data:/bitnami
    depends_on:
      - zookeeper
    restart: on-failure
    networks:
      - exchange
  # kafka Exporter
  kafexporter:
    image: bitnami/kafka-exporter:latest
    depends_on:
      - kafka
      - prometheus
    environment:
      - KAFKA_BROKER=kafka:9092
      - KAFKA_EXPORTER_LISTEN_ADDRESS=kafexporter:9308
    restart: on-failure
    networks:
      - exchange

  # Promethius: https://hub.docker.com/r/bitnami/prometheus
  prometheus:
    build: ./games_prometheus
    ports:
      - "9090:9090"
    volumes:
      - pro_data:/etc/prometheus_data
    restart: on-failure
    networks:
      - exchange

  # Grafana
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    volumes:
      - graf_data:/var/lib/grafana
    networks:
      - exchange

volumes:
  db_data: {}
  kafka_data: {}
  zoo_data: {}
  pro_data: {}
  graf_data: {}
networks:
  exchange:
    driver: bridge
