version: "3"
services:
  # Proxy
  proxy:
    build: ./games_proxy
    ports:
      - "80:80"
    depends_on:
      - api0
      - api1
      - api2
    networks:
      - exchange
  # APIS
  api0:
    build: ./games_api
    ports:
      - "8080"
    depends_on:
      - database
      - email
    networks:
      - exchange
  api1:
    build: ./games_api
    ports:
      - "8080"
    depends_on:
      - database
      - email
    networks:
      - exchange
  api2:
    build: ./games_api
    ports:
      - "8080"
    depends_on:
      - database
      - email
    networks:
      - exchange
  # DataBase
  database:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - db_data:/data/db
    networks:
      - exchange
  # Email Service
  email:
    build: ./games_email
    ports:
      - "8081"
    networks:
      - exchange
  # Zoo Keeper: https://hub.docker.com/r/bitnami/zookeeper !!might not be needed!!
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - "2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - zoo_data:/bitnami
    networks:
      - exchange
  # Kafka: https://hub.docker.com/r/bitnami/kafka
  kafka:
    image: bitnami/kafka:latest
    ports:
      - "9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    volumes:
      - kafka_data:/bitnami
    depends_on:
      - zookeeper
    networks:
      - exchange
    # Promethius: https://hub.docker.com/r/bitnami/prometheus
  # prometheus:
  #   image: bitnami/prometheus:latest
  #   ports:
  #     - "9090"
volumes:
  db_data: {}
  kafka_data: {}
  zoo_data: {}
networks:
  exchange:
    driver: bridge
